test:
  name: fastFabric
  description: This is benchmark for fastFabric
  workers:
    type: local
    number: 5
  rounds:
    - label: create_asset
      description: benchmark createAsset invoke call
      txNumber: 5000
      rateControl:
        type: fixed-rate
        opts:
          tps: 500
      workload:
        module: scripts/createAsset.js